version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: db-ports
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: quest_reservations_db
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"

  redis:
    image: redis
    container_name: redis-ports
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "12345"]
    environment:
      REDIS_PASSWORD: 12345
    ports:
      - "6379:6379"

volumes:
  mysql_data:
